[server]
headless = true
address = "localhost"  # Changed from "0.0.0.0"
port = 8501           # Changed from 5000

[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
